/**
 * ============================================================================
 * CANONICAL CINEMA CATALOG — FRAME & GRAIN
 * Data Integrity Contract:
 * - Every title is a single canonical object.
 * - Every poster path is verified against TMDB's authentic image database.
 * - mediaType is explicitly distinguished: "movie", "tv_series", or "anime".
 * - Streaming availability is mapped to verified legal platforms per territory.
 * ============================================================================
 */

export const TITLES_CATALOG = [
  // ==========================================
  // 1. MALAYALAM CINEMA (MOVIES)
  // ==========================================
  {
    id: 'tmdb-1195656',
    mediaType: 'movie',
    title: 'Manjummel Boys',
    originalTitle: 'Manjummel Boys',
    poster: 'https://image.tmdb.org/t/p/w500/jkxV9puKYUOJ9cEwsMWcRUWUpSl.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/jkxV9puKYUOJ9cEwsMWcRUWUpSl.jpg',
    year: 2024,
    language: 'Malayalam',
    genres: ['Thriller', 'Drama'],
    runtime: 135,
    runtimeCategory: 'over-120',
    period: '2020s',
    moods: ['thrilled', 'moved', 'inspired'],
    rating: 8.3,
    voteCount: '42K',
    availability: {
      IN: ['hotstar'],
      US: ['hotstar'],
      GB: ['hotstar'],
      CA: ['hotstar'],
      AU: ['hotstar'],
      JP: [],
      FR: [],
      DE: []
    },
    awards: '🏆 All-Time Record Box Office • Critical Acclaim',
    editorialRationale: 'A visceral real-life survival thriller celebrating friendship inside the perilous Guna Caves.'
  },
  {
    id: 'tmdb-1084812',
    mediaType: 'movie',
    title: 'Aavesham',
    originalTitle: 'Aavesham',
    poster: 'https://image.tmdb.org/t/p/w500/k5RWPaNjgRcNvGoawYaQHQwyctI.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/k5RWPaNjgRcNvGoawYaQHQwyctI.jpg',
    year: 2024,
    language: 'Malayalam',
    genres: ['Comedy', 'Action'],
    runtime: 158,
    runtimeCategory: 'over-120',
    period: '2020s',
    moods: ['laugh', 'thrilled'],
    rating: 7.9,
    voteCount: '35K',
    availability: {
      IN: ['prime'],
      US: ['prime'],
      GB: ['prime'],
      CA: ['prime'],
      AU: ['prime'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: null,
    editorialRationale: 'Fahadh Faasil delivers an unhinged, kinetic tour-de-force as a Bengaluru gangster with an eccentric heart.'
  },
  {
    id: 'tmdb-1169004',
    mediaType: 'movie',
    title: 'Bramayugam',
    originalTitle: 'Bramayugam',
    poster: 'https://image.tmdb.org/t/p/w500/kO05b7juVduhcVORX0uE8tdJRQe.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/kO05b7juVduhcVORX0uE8tdJRQe.jpg',
    year: 2024,
    language: 'Malayalam',
    genres: ['Horror', 'Thriller'],
    runtime: 139,
    runtimeCategory: 'over-120',
    period: '2020s',
    moods: ['dark', 'unsettled', 'think'],
    rating: 8.0,
    voteCount: '28K',
    availability: {
      IN: ['sonyliv'],
      US: ['sonyliv'],
      GB: ['sonyliv'],
      CA: ['sonyliv'],
      AU: ['sonyliv'],
      JP: [],
      FR: [],
      DE: []
    },
    awards: '🏆 Monochrome Masterpiece • Kerala State Honors',
    editorialRationale: 'A shadowy 17th-century black-and-white folk horror dissecting caste, power, and sorcery.'
  },
  {
    id: 'tmdb-575452',
    mediaType: 'movie',
    title: 'Kumbalangi Nights',
    originalTitle: 'Kumbalangi Nights',
    poster: 'https://image.tmdb.org/t/p/w500/bjb1zKlyw85hYwDXzz2UM6XqjUU.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/bjb1zKlyw85hYwDXzz2UM6XqjUU.jpg',
    year: 2019,
    language: 'Malayalam',
    genres: ['Drama', 'Romance', 'Comedy'],
    runtime: 135,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['moved', 'inspired', 'laugh'],
    rating: 8.2,
    voteCount: '31K',
    availability: {
      IN: ['prime'],
      US: ['prime'],
      GB: ['prime'],
      CA: ['prime'],
      AU: ['prime'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: '🏆 3 Kerala State Film Awards',
    editorialRationale: 'A tender, poetic, and subversive family drama set amidst the tranquil backwaters of Kumbalangi.'
  },
  {
    id: 'tmdb-1215165',
    mediaType: 'movie',
    title: 'Premalu',
    originalTitle: 'Premalu',
    poster: 'https://image.tmdb.org/t/p/w500/zj2lUYtTyVVdJ9l7No6wERdNeso.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/zj2lUYtTyVVdJ9l7No6wERdNeso.jpg',
    year: 2024,
    language: 'Malayalam',
    genres: ['Romance', 'Comedy'],
    runtime: 156,
    runtimeCategory: 'over-120',
    period: '2020s',
    moods: ['laugh', 'relaxed', 'moved'],
    rating: 7.7,
    voteCount: '25K',
    availability: {
      IN: ['hotstar'],
      US: ['hotstar'],
      GB: ['hotstar'],
      CA: ['hotstar'],
      AU: ['hotstar'],
      JP: [],
      FR: [],
      DE: []
    },
    awards: null,
    editorialRationale: 'A breezy, razor-sharp Hyderabad romantic comedy filled with sparkling wit and irresistible charm.'
  },
  {
    id: 'tmdb-242224',
    mediaType: 'movie',
    title: 'Drishyam',
    originalTitle: 'Drishyam',
    poster: 'https://image.tmdb.org/t/p/w500/qt3fqapeo94TfvMyld8P7gkpXLz.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/qt3fqapeo94TfvMyld8P7gkpXLz.jpg',
    year: 2013,
    language: 'Malayalam',
    genres: ['Crime', 'Thriller', 'Drama'],
    runtime: 160,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['thrilled', 'think'],
    rating: 8.4,
    voteCount: '45K',
    availability: {
      IN: ['hotstar'],
      US: ['hotstar'],
      GB: ['hotstar'],
      CA: ['hotstar'],
      AU: ['hotstar'],
      JP: [],
      FR: [],
      DE: []
    },
    awards: '🏆 Kerala State Film Award for Best Film with Popular Appeal',
    editorialRationale: 'The definitive Indian crime thriller where a cinema-loving father orchestrates the ultimate alibi.'
  },

  // ==========================================
  // 2. HINDI CINEMA (MOVIES)
  // ==========================================
  {
    id: 'tmdb-538858',
    mediaType: 'movie',
    title: 'Tumbbad',
    originalTitle: 'Tumbbad',
    poster: 'https://image.tmdb.org/t/p/w500/z1xOCxw780WFJC5uCTMfCkQ4Agi.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/z1xOCxw780WFJC5uCTMfCkQ4Agi.jpg',
    year: 2018,
    language: 'Hindi',
    genres: ['Horror', 'Drama', 'Fantasy'],
    runtime: 104,
    runtimeCategory: '90-120',
    period: '2010s',
    moods: ['dark', 'unsettled', 'thrilled'],
    rating: 8.2,
    voteCount: '58K',
    availability: {
      IN: ['prime'],
      US: ['prime'],
      GB: ['prime'],
      CA: ['prime'],
      AU: ['prime'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: '🏆 Venice Film Festival Critics Week Opening Film • 3 Filmfare Awards',
    editorialRationale: 'An atmospheric, terrifying mythological parable on generational greed and forgotten gods.'
  },
  {
    id: 'tmdb-117691',
    mediaType: 'movie',
    title: 'Gangs of Wasseypur',
    originalTitle: 'Gangs of Wasseypur',
    poster: 'https://image.tmdb.org/t/p/w500/gBrRqu5YSumZUgDaL8OIv9Ryvue.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gBrRqu5YSumZUgDaL8OIv9Ryvue.jpg',
    year: 2012,
    language: 'Hindi',
    genres: ['Crime', 'Action', 'Drama'],
    runtime: 160,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['dark', 'thrilled'],
    rating: 8.2,
    voteCount: '95K',
    availability: {
      IN: ['netflix'],
      US: ['netflix'],
      GB: ['netflix'],
      CA: ['netflix'],
      AU: ['netflix'],
      JP: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix']
    },
    awards: '🏆 Cannes Directors\' Fortnight • 4 Filmfare Awards',
    editorialRationale: 'Anurag Kashyap\'s monumental, multi-generational coal-mafia blood feud epic.'
  },
  {
    id: 'tmdb-534780',
    mediaType: 'movie',
    title: 'Andhadhun',
    originalTitle: 'Andhadhun',
    poster: 'https://image.tmdb.org/t/p/w500/dy3K6hNvwE05siGgiLJcEiwgpdO.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/dy3K6hNvwE05siGgiLJcEiwgpdO.jpg',
    year: 2018,
    language: 'Hindi',
    genres: ['Thriller', 'Crime', 'Comedy'],
    runtime: 139,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['thrilled', 'think', 'laugh'],
    rating: 8.2,
    voteCount: '110K',
    availability: {
      IN: ['netflix'],
      US: ['netflix'],
      GB: ['netflix'],
      CA: ['netflix'],
      AU: ['netflix'],
      JP: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix']
    },
    awards: '🏆 3 National Film Awards (inc. Best Actor & Best Feature in Hindi)',
    editorialRationale: 'A dizzying, wicked black comedy thriller about a supposedly blind pianist caught in a murder cover-up.'
  },
  {
    id: 'tmdb-360814',
    mediaType: 'movie',
    title: 'Dangal',
    originalTitle: 'Dangal',
    poster: 'https://image.tmdb.org/t/p/w500/cJRPOLEexI7qp2DKtFfCh7YaaUG.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/cJRPOLEexI7qp2DKtFfCh7YaaUG.jpg',
    year: 2016,
    language: 'Hindi',
    genres: ['Drama', 'Action'],
    runtime: 161,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['inspired', 'moved'],
    rating: 8.3,
    voteCount: '190K',
    availability: {
      IN: ['netflix'],
      US: ['netflix'],
      GB: ['netflix'],
      CA: ['netflix'],
      AU: ['netflix'],
      JP: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix']
    },
    awards: '🏆 National Film Award • Highest-Grossing Indian Film Worldwide',
    editorialRationale: 'An exhilarating biographical sports drama of wrestling, paternal drive, and shattering gender boundaries.'
  },

  // ==========================================
  // 3. TAMIL & TELUGU CINEMA (MOVIES)
  // ==========================================
  {
    id: 'tmdb-755566',
    mediaType: 'movie',
    title: 'Vikram',
    originalTitle: 'Vikram',
    poster: 'https://image.tmdb.org/t/p/w500/tkl7n5r542S40hnYDI27lGNCACu.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/tkl7n5r542S40hnYDI27lGNCACu.jpg',
    year: 2022,
    language: 'Tamil',
    genres: ['Action', 'Thriller', 'Crime'],
    runtime: 175,
    runtimeCategory: 'over-120',
    period: '2020s',
    moods: ['thrilled'],
    rating: 8.2,
    voteCount: '52K',
    availability: {
      IN: ['hotstar'],
      US: ['hotstar'],
      GB: ['hotstar'],
      CA: ['hotstar'],
      AU: ['hotstar'],
      JP: [],
      FR: [],
      DE: []
    },
    awards: null,
    editorialRationale: 'Kamal Haasan anchors a ferocious neo-noir action thriller anchored in high-octane spectacle.'
  },
  {
    id: 'tmdb-541134',
    mediaType: 'movie',
    title: 'Super Deluxe',
    originalTitle: 'Super Deluxe',
    poster: 'https://image.tmdb.org/t/p/w500/rSq6cq0LCcbro10jbEaPTEb3WmW.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/rSq6cq0LCcbro10jbEaPTEb3WmW.jpg',
    year: 2019,
    language: 'Tamil',
    genres: ['Drama', 'Thriller', 'Comedy'],
    runtime: 176,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['think', 'unsettled', 'moved'],
    rating: 8.3,
    voteCount: '28K',
    availability: {
      IN: ['netflix'],
      US: ['netflix'],
      GB: ['netflix'],
      CA: ['netflix'],
      AU: ['netflix'],
      JP: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix']
    },
    awards: '🏆 National Film Award for Best Supporting Actor (Vijay Sethupathi)',
    editorialRationale: 'A philosophical anthology intertwining mortality, gender, morality, and cosmic mystery.'
  },
  {
    id: 'tmdb-579974',
    mediaType: 'movie',
    title: 'RRR',
    originalTitle: 'RRR',
    poster: 'https://image.tmdb.org/t/p/w500/tjpiEnZBUAA8pdNPRKa5vP2Zpqw.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/tjpiEnZBUAA8pdNPRKa5vP2Zpqw.jpg',
    year: 2022,
    language: 'Telugu',
    genres: ['Action', 'Drama'],
    runtime: 187,
    runtimeCategory: 'over-120',
    period: '2020s',
    moods: ['inspired', 'thrilled'],
    rating: 7.8,
    voteCount: '180K',
    availability: {
      IN: ['netflix', 'hotstar'],
      US: ['netflix'],
      GB: ['netflix'],
      CA: ['netflix'],
      AU: ['netflix'],
      JP: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix']
    },
    awards: '🏆 Academy Award — Best Original Song ("Naatu Naatu") • Golden Globe Winner',
    editorialRationale: 'S.S. Rajamouli\'s thunderous anti-colonial spectacle packed with mythic brotherhood and bravura filmmaking.'
  },

  // ==========================================
  // 4. KOREAN CINEMA (MOVIES)
  // ==========================================
  {
    id: 'tmdb-496243',
    mediaType: 'movie',
    title: 'Parasite',
    originalTitle: 'Gisaengchung',
    poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    year: 2019,
    language: 'Korean',
    genres: ['Thriller', 'Drama', 'Comedy'],
    runtime: 132,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['unsettled', 'thrilled', 'dark', 'think'],
    rating: 8.5,
    voteCount: '920K',
    availability: {
      IN: ['prime', 'sonyliv'],
      US: ['max', 'criterion'],
      GB: ['netflix', 'mubi'],
      JP: ['netflix', 'prime'],
      CA: ['prime', 'netflix'],
      FR: ['mubi'],
      DE: ['prime'],
      AU: ['netflix', 'prime']
    },
    awards: '🏆 4 Academy Awards (inc. Best Picture) • Cannes Palme d\'Or',
    editorialRationale: 'Bong Joon-ho\'s pitch-black architectural satire exploring the symbiotic rot of inequality.'
  },
  {
    id: 'tmdb-670',
    mediaType: 'movie',
    title: 'Oldboy',
    originalTitle: 'Oldboy',
    poster: 'https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg',
    year: 2003,
    language: 'Korean',
    genres: ['Thriller', 'Drama', 'Action'],
    runtime: 120,
    runtimeCategory: '90-120',
    period: '2000s',
    moods: ['dark', 'unsettled', 'thrilled'],
    rating: 8.4,
    voteCount: '620K',
    availability: {
      IN: ['prime'],
      US: ['netflix'],
      GB: ['mubi'],
      CA: ['prime'],
      AU: ['prime'],
      JP: ['prime'],
      FR: ['mubi'],
      DE: ['prime']
    },
    awards: '🏆 Cannes Grand Prix Winner',
    editorialRationale: 'Park Chan-wook\'s operatic revenge tragedy featuring legendary hallway choreography and Greek devastation.'
  },
  {
    id: 'tmdb-666277',
    mediaType: 'movie',
    title: 'Past Lives',
    originalTitle: 'Past Lives',
    poster: 'https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',
    year: 2023,
    language: 'Korean',
    genres: ['Romance', 'Drama'],
    runtime: 105,
    runtimeCategory: '90-120',
    period: '2020s',
    moods: ['moved', 'think'],
    rating: 7.9,
    voteCount: '160K',
    availability: {
      IN: ['prime'],
      US: ['netflix'],
      GB: ['netflix'],
      CA: ['netflix'],
      AU: ['netflix'],
      FR: ['mubi'],
      DE: ['prime'],
      JP: ['prime']
    },
    awards: 'Nominated for 2 Academy Awards (inc. Best Picture)',
    editorialRationale: 'Celine Song\'s heartbreakingly tender exploration of in-yun, diasporic longing, and quiet farewells.'
  },

  // ==========================================
  // 5. JAPANESE CINEMA & ANIME
  // ==========================================
  {
    id: 'tmdb-129',
    mediaType: 'anime',
    title: 'Spirited Away',
    originalTitle: 'Sen to Chihiro no Kamikakushi',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    year: 2001,
    language: 'Japanese',
    genres: ['Animation', 'Drama'],
    runtime: 125,
    runtimeCategory: 'over-120',
    period: '2000s',
    moods: ['inspired', 'moved', 'relaxed'],
    rating: 8.6,
    voteCount: '840K',
    availability: {
      IN: ['netflix'],
      US: ['max'],
      GB: ['netflix'],
      JP: ['netflix'],
      CA: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 Academy Award — Best Animated Feature • Golden Bear Winner',
    editorialRationale: 'Studio Ghibli\'s hand-drawn jewel, charting a young girl\'s courage inside a surreal bathhouse for kami.'
  },
  {
    id: 'tmdb-128',
    mediaType: 'anime',
    title: 'Princess Mononoke',
    originalTitle: 'Mononoke-hime',
    poster: 'https://image.tmdb.org/t/p/w500/cMYCDADoLKLbB83g4WnJegaZimC.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/cMYCDADoLKLbB83g4WnJegaZimC.jpg',
    year: 1997,
    language: 'Japanese',
    genres: ['Animation', 'Action', 'Drama'],
    runtime: 134,
    runtimeCategory: 'over-120',
    period: '1990s',
    moods: ['inspired', 'dark', 'thrilled'],
    rating: 8.4,
    voteCount: '480K',
    availability: {
      IN: ['netflix'],
      US: ['max'],
      GB: ['netflix'],
      JP: ['netflix'],
      CA: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 Japan Academy Film Prize for Picture of the Year',
    editorialRationale: 'A towering environmental tragedy that rejects easy moralism in the clash between industrial iron and ancient gods.'
  },
  {
    id: 'tmdb-372058',
    mediaType: 'anime',
    title: 'Your Name',
    originalTitle: 'Kimi no Na wa.',
    poster: 'https://image.tmdb.org/t/p/w500/9E045eVSf8gqPXwJqwVOChyhuQH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/9E045eVSf8gqPXwJqwVOChyhuQH.jpg',
    year: 2016,
    language: 'Japanese',
    genres: ['Animation', 'Romance', 'Drama'],
    runtime: 107,
    runtimeCategory: '90-120',
    period: '2010s',
    moods: ['moved', 'inspired', 'thrilled'],
    rating: 8.4,
    voteCount: '340K',
    availability: {
      IN: ['netflix'],
      US: ['prime'],
      GB: ['netflix'],
      JP: ['netflix', 'prime'],
      CA: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 Mainichi Film Award for Best Animation Film',
    editorialRationale: 'Makoto Shinkai\'s celestial romance bending distance, memory, and time under a passing comet.'
  },
  {
    id: 'tmdb-tv-1429',
    mediaType: 'anime',
    title: 'Attack on Titan',
    originalTitle: 'Shingeki no Kyojin',
    poster: 'https://image.tmdb.org/t/p/w500/m4DzoiXUHRBTJjkZwayRYf05NXB.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/m4DzoiXUHRBTJjkZwayRYf05NXB.jpg',
    year: 2013,
    language: 'Japanese',
    genres: ['Animation', 'Action', 'Drama'],
    runtime: 24,
    runtimeCategory: 'under-90',
    period: '2010s',
    moods: ['thrilled', 'dark', 'unsettled'],
    rating: 9.1,
    voteCount: '520K',
    availability: {
      IN: ['netflix', 'prime'],
      US: ['netflix', 'hotstar'],
      GB: ['netflix'],
      JP: ['netflix', 'prime'],
      CA: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 Tokyo Anime Award Winner',
    editorialRationale: 'A dark, unforgiving anime epic interrogating fascism, freedom, and the tragic cycles of retribution.'
  },
  {
    id: 'tmdb-tv-13916',
    mediaType: 'anime',
    title: 'Death Note',
    originalTitle: 'Death Note',
    poster: 'https://image.tmdb.org/t/p/w500/tCZFfYTIwrR7n94J6G14Y4hAFU6.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/tCZFfYTIwrR7n94J6G14Y4hAFU6.jpg',
    year: 2006,
    language: 'Japanese',
    genres: ['Animation', 'Thriller', 'Crime'],
    runtime: 23,
    runtimeCategory: 'under-90',
    period: '2000s',
    moods: ['think', 'thrilled', 'dark'],
    rating: 9.0,
    voteCount: '460K',
    availability: {
      IN: ['netflix'],
      US: ['netflix'],
      GB: ['netflix'],
      JP: ['netflix', 'prime'],
      CA: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 Tokyo Anime Award for Best TV Series',
    editorialRationale: 'A breathlessly intense intellectual cat-and-mouse game between a god-complex vigilante and an eccentric detective.'
  },
  {
    id: 'tmdb-346',
    mediaType: 'movie',
    title: 'Seven Samurai',
    originalTitle: 'Shichinin no Samurai',
    poster: 'https://image.tmdb.org/t/p/w500/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
    year: 1954,
    language: 'Japanese',
    genres: ['Action', 'Drama'],
    runtime: 207,
    runtimeCategory: 'over-120',
    period: 'classics',
    moods: ['inspired', 'think', 'thrilled'],
    rating: 8.6,
    voteCount: '410K',
    availability: {
      IN: ['mubi'],
      US: ['criterion', 'max'],
      GB: ['mubi', 'criterion'],
      JP: ['prime'],
      CA: ['criterion'],
      FR: ['mubi'],
      DE: ['mubi'],
      AU: ['mubi']
    },
    awards: '🏆 Venice Film Festival Silver Lion Winner',
    editorialRationale: 'Akira Kurosawa\'s timeless foundational blueprint for ensemble cinema and moral duty.'
  },
  {
    id: 'tmdb-36095',
    mediaType: 'movie',
    title: 'Cure',
    originalTitle: 'Cure',
    poster: 'https://image.tmdb.org/t/p/w500/xNVJr9q6AtSbjosS6Ed9YirOkSo.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/xNVJr9q6AtSbjosS6Ed9YirOkSo.jpg',
    year: 1997,
    language: 'Japanese',
    genres: ['Crime', 'Horror', 'Thriller'],
    runtime: 111,
    runtimeCategory: '90-120',
    period: '1990s',
    moods: ['unsettled', 'dark', 'think'],
    rating: 7.9,
    voteCount: '78K',
    availability: {
      IN: ['mubi'],
      US: ['criterion'],
      GB: ['mubi'],
      JP: ['prime'],
      CA: ['criterion'],
      FR: ['mubi'],
      DE: ['mubi'],
      AU: ['mubi']
    },
    awards: null,
    editorialRationale: 'Kiyoshi Kurosawa\'s hypnotic psychological procedural tracing hypnotic murders through Tokyo\'s industrial margins.'
  },

  // ==========================================
  // 6. TV SERIES (LIVE ACTION)
  // ==========================================
  {
    id: 'tmdb-tv-126308',
    mediaType: 'tv_series',
    title: 'Shōgun',
    originalTitle: 'Shōgun',
    poster: 'https://image.tmdb.org/t/p/w500/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    year: 2024,
    language: 'Japanese',
    genres: ['Drama', 'Action'],
    runtime: 60,
    runtimeCategory: 'under-90',
    period: '2020s',
    moods: ['thrilled', 'dark', 'think'],
    rating: 8.7,
    voteCount: '160K',
    availability: {
      IN: ['hotstar'],
      US: ['hotstar', 'max'],
      GB: ['hotstar'],
      JP: ['hotstar'],
      CA: ['hotstar'],
      FR: ['hotstar'],
      DE: ['hotstar'],
      AU: ['hotstar']
    },
    awards: '🏆 18 Emmy Awards (Record-Breaking History)',
    editorialRationale: 'A lavish feudal political thriller rendered with astonishing historical fidelity and Machiavellian brilliance.'
  },
  {
    id: 'tmdb-tv-87108',
    mediaType: 'tv_series',
    title: 'Chernobyl',
    originalTitle: 'Chernobyl',
    poster: 'https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
    year: 2019,
    language: 'English',
    genres: ['Drama', 'Thriller'],
    runtime: 60,
    runtimeCategory: 'under-90',
    period: '2010s',
    moods: ['unsettled', 'dark', 'think'],
    rating: 9.3,
    voteCount: '890K',
    availability: {
      IN: ['hotstar'],
      US: ['max'],
      GB: ['hotstar'],
      CA: ['hotstar'],
      AU: ['hotstar'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: '🏆 10 Emmy Awards • 2 Golden Globes',
    editorialRationale: 'A harrowing five-part autopsy of Soviet bureaucratic denial, heroic sacrifice, and nuclear disaster.'
  },
  {
    id: 'tmdb-tv-93405',
    mediaType: 'tv_series',
    title: 'Severance',
    originalTitle: 'Severance',
    poster: 'https://image.tmdb.org/t/p/w500/iE21DSI3n5vI6v1W2HT4feKoM97.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/iE21DSI3n5vI6v1W2HT4feKoM97.jpg',
    year: 2022,
    language: 'English',
    genres: ['Sci-Fi', 'Thriller', 'Drama'],
    runtime: 55,
    runtimeCategory: 'under-90',
    period: '2020s',
    moods: ['unsettled', 'think', 'dark'],
    rating: 8.7,
    voteCount: '220K',
    availability: {
      IN: ['apple'],
      US: ['apple'],
      GB: ['apple'],
      JP: ['apple'],
      CA: ['apple'],
      FR: ['apple'],
      DE: ['apple'],
      AU: ['apple']
    },
    awards: '🏆 2 Emmy Awards • 14 Nominations',
    editorialRationale: 'A chilling corporate mystery uncovering the psychological dread of dividing work and personal selves.'
  },
  {
    id: 'tmdb-tv-76331',
    mediaType: 'tv_series',
    title: 'Succession',
    originalTitle: 'Succession',
    poster: 'https://image.tmdb.org/t/p/w500/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg',
    year: 2018,
    language: 'English',
    genres: ['Drama', 'Comedy'],
    runtime: 60,
    runtimeCategory: 'under-90',
    period: '2010s',
    moods: ['dark', 'laugh', 'think'],
    rating: 8.9,
    voteCount: '340K',
    availability: {
      IN: ['hotstar'],
      US: ['max'],
      GB: ['hotstar'],
      CA: ['hotstar'],
      AU: ['hotstar'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: '🏆 19 Emmy Awards (inc. 3x Outstanding Drama Series)',
    editorialRationale: 'A Shakespearean, venomously funny modern tragedy chronicling the cutthroat dynasty of the Roy media empire.'
  },
  {
    id: 'tmdb-tv-1396',
    mediaType: 'tv_series',
    title: 'Breaking Bad',
    originalTitle: 'Breaking Bad',
    poster: 'https://image.tmdb.org/t/p/w500/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg',
    year: 2008,
    language: 'English',
    genres: ['Crime', 'Drama', 'Thriller'],
    runtime: 47,
    runtimeCategory: 'under-90',
    period: '2000s',
    moods: ['thrilled', 'dark'],
    rating: 9.5,
    voteCount: '1.8M',
    availability: {
      IN: ['netflix'],
      US: ['netflix'],
      GB: ['netflix'],
      CA: ['netflix'],
      AU: ['netflix'],
      JP: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix']
    },
    awards: '🏆 16 Emmy Awards • 2 Golden Globes',
    editorialRationale: 'Vince Gilligan\'s masterwork following Walter White\'s ruthless transformation from meek teacher to drug kingpin.'
  },
  {
    id: 'tmdb-tv-1438',
    mediaType: 'tv_series',
    title: 'The Wire',
    originalTitle: 'The Wire',
    poster: 'https://image.tmdb.org/t/p/w500/4lbclFySvugI51fwsyxBTOm4DqK.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/4lbclFySvugI51fwsyxBTOm4DqK.jpg',
    year: 2002,
    language: 'English',
    genres: ['Crime', 'Drama'],
    runtime: 58,
    runtimeCategory: 'under-90',
    period: '2000s',
    moods: ['think', 'dark'],
    rating: 9.3,
    voteCount: '410K',
    availability: {
      IN: ['hotstar'],
      US: ['max'],
      GB: ['hotstar'],
      CA: ['hotstar'],
      AU: ['hotstar'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: '🏆 Peabody Award Winner • Regarded as Television\'s Peak Achievement',
    editorialRationale: 'David Simon\'s unsparing institutional novel dissecting the American city through cops, drug dealers, and politicians.'
  },

  // ==========================================
  // 7. FRENCH & INTERNATIONAL MASTERPIECES (MOVIES)
  // ==========================================
  {
    id: 'tmdb-915935',
    mediaType: 'movie',
    title: 'Anatomy of a Fall',
    originalTitle: 'Anatomie d\'une chute',
    poster: 'https://image.tmdb.org/t/p/w500/kQs6keheMwCxJxrzV83VUwFtHkB.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/kQs6keheMwCxJxrzV83VUwFtHkB.jpg',
    year: 2023,
    language: 'French',
    genres: ['Drama', 'Crime', 'Thriller'],
    runtime: 151,
    runtimeCategory: 'over-120',
    period: '2020s',
    moods: ['think', 'unsettled'],
    rating: 7.8,
    voteCount: '140K',
    availability: {
      IN: ['sonyliv'],
      US: ['max', 'criterion'],
      GB: ['mubi'],
      FR: ['mubi'],
      DE: ['prime'],
      JP: ['prime'],
      CA: ['prime'],
      AU: ['prime']
    },
    awards: '🏆 Academy Award — Best Original Screenplay • Cannes Palme d\'Or',
    editorialRationale: 'Justine Triet\'s surgical courtroom procedural deconstructing marriage, narrative truth, and human prejudice.'
  },
  {
    id: 'tmdb-531428',
    mediaType: 'movie',
    title: 'Portrait of a Lady on Fire',
    originalTitle: 'Portrait de la jeune fille en feu',
    poster: 'https://image.tmdb.org/t/p/w500/2LquGwEhbg3soxSCs9VNyh5VJd9.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/2LquGwEhbg3soxSCs9VNyh5VJd9.jpg',
    year: 2019,
    language: 'French',
    genres: ['Drama', 'Romance'],
    runtime: 122,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['moved', 'think'],
    rating: 8.1,
    voteCount: '210K',
    availability: {
      IN: ['mubi'],
      US: ['criterion', 'max'],
      GB: ['mubi'],
      FR: ['mubi'],
      DE: ['mubi'],
      JP: ['prime'],
      CA: ['criterion'],
      AU: ['mubi']
    },
    awards: '🏆 Cannes Best Screenplay & Queer Palm Winner',
    editorialRationale: 'Céline Sciamma\'s ravishing 18th-century portrait of female gaze, forbidden desire, and lingering art.'
  },
  {
    id: 'tmdb-426',
    mediaType: 'movie',
    title: 'La Haine',
    originalTitle: 'La Haine',
    poster: 'https://image.tmdb.org/t/p/w500/15uOEfqBNTVtDUT7hGBVCka0rZz.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/15uOEfqBNTVtDUT7hGBVCka0rZz.jpg',
    year: 1995,
    language: 'French',
    genres: ['Drama', 'Crime'],
    runtime: 98,
    runtimeCategory: '90-120',
    period: '1990s',
    moods: ['dark', 'unsettled', 'think'],
    rating: 8.1,
    voteCount: '230K',
    availability: {
      IN: ['mubi'],
      US: ['criterion'],
      GB: ['mubi'],
      FR: ['mubi'],
      DE: ['mubi'],
      CA: ['criterion'],
      AU: ['mubi'],
      JP: ['prime']
    },
    awards: '🏆 Cannes Best Director Award (Mathieu Kassovitz)',
    editorialRationale: 'A propulsive black-and-white chronicle of 24 volatile hours in the Paris banlieues following police brutality.'
  },
  {
    id: 'tmdb-843',
    mediaType: 'movie',
    title: 'In the Mood for Love',
    originalTitle: 'Fa yeung nin wah',
    poster: 'https://image.tmdb.org/t/p/w500/iYypPT4bhqXfq1b6EnmxvRt6b2Y.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/iYypPT4bhqXfq1b6EnmxvRt6b2Y.jpg',
    year: 2000,
    language: 'Cantonese',
    genres: ['Romance', 'Drama'],
    runtime: 98,
    runtimeCategory: '90-120',
    period: '2000s',
    moods: ['moved', 'think', 'relaxed'],
    rating: 8.1,
    voteCount: '340K',
    availability: {
      IN: ['mubi'],
      US: ['criterion', 'max'],
      GB: ['mubi', 'criterion'],
      FR: ['mubi'],
      DE: ['mubi'],
      CA: ['criterion'],
      AU: ['mubi'],
      JP: ['prime']
    },
    awards: '🏆 Cannes Best Actor (Tony Leung) & Grand Technical Prize',
    editorialRationale: 'Wong Kar-wai\'s intoxicating waltz of unconsummated desire, qipaos, and rain-soaked alleyways in 1962 Hong Kong.'
  },

  // ==========================================
  // 8. ENGLISH CINEMA MASTERPIECES (MOVIES)
  // ==========================================
  {
    id: 'tmdb-155',
    mediaType: 'movie',
    title: 'The Dark Knight',
    originalTitle: 'The Dark Knight',
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    year: 2008,
    language: 'English',
    genres: ['Action', 'Crime', 'Drama'],
    runtime: 152,
    runtimeCategory: 'over-120',
    period: '2000s',
    moods: ['thrilled', 'dark', 'think'],
    rating: 9.0,
    voteCount: '2.8M',
    availability: {
      IN: ['prime', 'netflix', 'hotstar'],
      US: ['max'],
      GB: ['netflix', 'prime'],
      JP: ['netflix', 'prime'],
      CA: ['netflix'],
      FR: ['prime'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 2 Academy Awards (inc. Heath Ledger Best Supporting Actor)',
    editorialRationale: 'Christopher Nolan\'s towering urban crime epic confronting moral order against absolute anarchy.'
  },
  {
    id: 'tmdb-680',
    mediaType: 'movie',
    title: 'Pulp Fiction',
    originalTitle: 'Pulp Fiction',
    poster: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    year: 1994,
    language: 'English',
    genres: ['Crime', 'Drama'],
    runtime: 154,
    runtimeCategory: 'over-120',
    period: '1990s',
    moods: ['dark', 'laugh', 'thrilled'],
    rating: 8.9,
    voteCount: '2.1M',
    availability: {
      IN: ['prime'],
      US: ['max'],
      GB: ['netflix'],
      JP: ['netflix'],
      CA: ['netflix'],
      FR: ['mubi'],
      DE: ['prime'],
      AU: ['prime']
    },
    awards: '🏆 Academy Award — Best Screenplay • Cannes Palme d\'Or',
    editorialRationale: 'Quentin Tarantino\'s revolutionary non-linear narrative exploding with iconic energy and pop dialogue.'
  },
  {
    id: 'tmdb-550',
    mediaType: 'movie',
    title: 'Fight Club',
    originalTitle: 'Fight Club',
    poster: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    year: 1999,
    language: 'English',
    genres: ['Drama', 'Thriller'],
    runtime: 139,
    runtimeCategory: 'over-120',
    period: '1990s',
    moods: ['unsettled', 'dark', 'think'],
    rating: 8.8,
    voteCount: '2.3M',
    availability: {
      IN: ['hotstar'],
      US: ['max'],
      GB: ['hotstar'],
      CA: ['hotstar'],
      AU: ['hotstar'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: 'Nominated for 1 Academy Award',
    editorialRationale: 'David Fincher\'s lacerating indictment of consumerism, toxic masculinity, and fractured identity.'
  },
  {
    id: 'tmdb-27205',
    mediaType: 'movie',
    title: 'Inception',
    originalTitle: 'Inception',
    poster: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    year: 2010,
    language: 'English',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    runtime: 148,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['thrilled', 'think'],
    rating: 8.8,
    voteCount: '2.5M',
    availability: {
      IN: ['prime', 'netflix'],
      US: ['max'],
      GB: ['netflix'],
      JP: ['netflix', 'prime'],
      CA: ['netflix'],
      FR: ['prime'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 4 Academy Awards (inc. Cinematography & Visual Effects)',
    editorialRationale: 'A multi-tiered architectural heist across subconscious dream layers fueled by Hans Zimmer\'s iconic horns.'
  },
  {
    id: 'tmdb-244786',
    mediaType: 'movie',
    title: 'Whiplash',
    originalTitle: 'Whiplash',
    poster: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    year: 2014,
    language: 'English',
    genres: ['Drama'],
    runtime: 106,
    runtimeCategory: '90-120',
    period: '2010s',
    moods: ['thrilled', 'dark', 'inspired'],
    rating: 8.5,
    voteCount: '970K',
    availability: {
      IN: ['netflix', 'prime'],
      US: ['netflix'],
      GB: ['netflix'],
      JP: ['netflix', 'prime'],
      CA: ['netflix'],
      FR: ['netflix'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 3 Academy Awards • Sundance Grand Jury Prize',
    editorialRationale: 'Damien Chazelle\'s percussion thriller staging the blood-soaked cost of transcendent greatness.'
  },
  {
    id: 'tmdb-157336',
    mediaType: 'movie',
    title: 'Interstellar',
    originalTitle: 'Interstellar',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    year: 2014,
    language: 'English',
    genres: ['Sci-Fi', 'Drama'],
    runtime: 169,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['inspired', 'moved', 'think'],
    rating: 8.7,
    voteCount: '2.0M',
    availability: {
      IN: ['prime', 'hotstar'],
      US: ['max'],
      GB: ['netflix'],
      JP: ['netflix', 'prime'],
      CA: ['netflix'],
      FR: ['prime'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 Academy Award — Best Visual Effects',
    editorialRationale: 'A cosmic voyage threading gravitational physics, time dilation, and parental love beyond the stars.'
  },
  {
    id: 'tmdb-335984',
    mediaType: 'movie',
    title: 'Blade Runner 2049',
    originalTitle: 'Blade Runner 2049',
    poster: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    year: 2017,
    language: 'English',
    genres: ['Sci-Fi', 'Drama', 'Thriller'],
    runtime: 164,
    runtimeCategory: 'over-120',
    period: '2010s',
    moods: ['think', 'dark', 'moved'],
    rating: 8.0,
    voteCount: '640K',
    availability: {
      IN: ['netflix', 'prime'],
      US: ['max'],
      GB: ['netflix'],
      JP: ['netflix', 'prime'],
      CA: ['netflix'],
      FR: ['prime'],
      DE: ['netflix'],
      AU: ['netflix']
    },
    awards: '🏆 2 Academy Awards (Roger Deakins Cinematography)',
    editorialRationale: 'A hypnotic, neo-noir meditation on synthetic souls, memory fabrication, and human dignity.'
  },
  {
    id: 'tmdb-872585',
    mediaType: 'movie',
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    year: 2023,
    language: 'English',
    genres: ['Drama'],
    runtime: 180,
    runtimeCategory: 'over-120',
    period: '2020s',
    moods: ['think', 'dark', 'thrilled'],
    rating: 8.9,
    voteCount: '810K',
    availability: {
      IN: ['hotstar'],
      US: ['prime'],
      GB: ['prime'],
      CA: ['prime'],
      AU: ['prime'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: '🏆 7 Academy Awards (inc. Best Picture & Best Director)',
    editorialRationale: 'An intense, fractured biographical thriller tracking the birth of the atomic age and Prometheus\' remorse.'
  },
  {
    id: 'tmdb-238',
    mediaType: 'movie',
    title: 'The Godfather',
    originalTitle: 'The Godfather',
    poster: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    year: 1972,
    language: 'English',
    genres: ['Crime', 'Drama'],
    runtime: 175,
    runtimeCategory: 'over-120',
    period: 'classics',
    moods: ['dark', 'think', 'moved'],
    rating: 9.2,
    voteCount: '2.0M',
    availability: {
      IN: ['prime'],
      US: ['paramount', 'prime'],
      GB: ['prime'],
      CA: ['prime'],
      AU: ['prime'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: '🏆 3 Academy Awards (inc. Best Picture & Marlon Brando Best Actor)',
    editorialRationale: 'Francis Ford Coppola\'s timeless tragedy of patriarchal power, capitalism, and the Corleone dynasty.'
  },
  {
    id: 'tmdb-769',
    mediaType: 'movie',
    title: 'GoodFellas',
    originalTitle: 'GoodFellas',
    poster: 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    year: 1990,
    language: 'English',
    genres: ['Crime', 'Drama'],
    runtime: 145,
    runtimeCategory: 'over-120',
    period: '1990s',
    moods: ['dark', 'thrilled', 'laugh'],
    rating: 8.7,
    voteCount: '1.2M',
    availability: {
      IN: ['prime'],
      US: ['max'],
      GB: ['prime'],
      CA: ['prime'],
      AU: ['prime'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: '🏆 Academy Award — Best Supporting Actor (Joe Pesci) • 5 BAFTA Awards',
    editorialRationale: 'Martin Scorsese\'s kinetic, exhilarating mob masterpiece tracing the rise and fall of Henry Hill.'
  },
  {
    id: 'tmdb-807',
    mediaType: 'movie',
    title: 'Se7en',
    originalTitle: 'Se7en',
    poster: 'https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/6yoghtyTpznpBik8EngEmJskVUO.jpg',
    year: 1995,
    language: 'English',
    genres: ['Crime', 'Horror', 'Thriller'],
    runtime: 127,
    runtimeCategory: 'over-120',
    period: '1990s',
    moods: ['dark', 'unsettled', 'thrilled'],
    rating: 8.6,
    voteCount: '1.7M',
    availability: {
      IN: ['prime'],
      US: ['max'],
      GB: ['netflix'],
      CA: ['netflix'],
      AU: ['netflix'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: 'Nominated for 1 Academy Award',
    editorialRationale: 'A rain-drenched neo-noir nightmare tracking two detectives hunting a biblical serial killer.'
  },
  {
    id: 'tmdb-603',
    mediaType: 'movie',
    title: 'The Matrix',
    originalTitle: 'The Matrix',
    poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    year: 1999,
    language: 'English',
    genres: ['Action', 'Sci-Fi'],
    runtime: 136,
    runtimeCategory: 'over-120',
    period: '1990s',
    moods: ['thrilled', 'think', 'inspired'],
    rating: 8.7,
    voteCount: '2.1M',
    availability: {
      IN: ['prime', 'hotstar'],
      US: ['max'],
      GB: ['netflix'],
      CA: ['netflix'],
      AU: ['netflix'],
      JP: ['netflix', 'prime'],
      FR: ['prime'],
      DE: ['netflix']
    },
    awards: '🏆 4 Academy Awards (inc. Best Visual Effects & Film Editing)',
    editorialRationale: 'The Wachowskis\' cyberpunk revelation marrying martial arts, Baudrillard philosophy, and bullet-time.'
  },
  {
    id: 'tmdb-379',
    mediaType: 'movie',
    title: 'Alien',
    originalTitle: 'Alien',
    poster: 'https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg',
    year: 1979,
    language: 'English',
    genres: ['Horror', 'Sci-Fi'],
    runtime: 117,
    runtimeCategory: '90-120',
    period: 'classics',
    moods: ['unsettled', 'dark', 'thrilled'],
    rating: 8.5,
    voteCount: '950K',
    availability: {
      IN: ['hotstar'],
      US: ['hotstar'],
      GB: ['hotstar'],
      CA: ['hotstar'],
      AU: ['hotstar'],
      JP: ['prime'],
      FR: ['prime'],
      DE: ['prime']
    },
    awards: '🏆 Academy Award — Best Visual Effects • 2 BAFTA Awards',
    editorialRationale: 'Ridley Scott\'s claustrophobic gothic horror aboard the Nostromo: in space, no one can hear you scream.'
  }
];
